### ISSUE TITLE
Coding of "wrong", "partially correct" and "correct"

### ISSUE THREAD

**Issue by ISNTACC** [ISN-Zurich/ISN-Learning-Cards#102]
Current Behavior:
All correct answers are highlighted green, the chosen ones blue.
Potential problems:
- depending on the number of answers, the user may end up with a screen full of grey and/or mostly green hooks, with the wrong blue ones further down and invisible. This in combination with a "wrong" or "partially wrong" statement. The combination of predominantly green hooks with any wrong or partially wrong statement may be confusing.

Recommended Behavior:
- Color coding of the smiley-versions in green, orange or red - depending on correctness of answer (this would also be somewhat in line with VBS standards).
- Option: Coloring of feedback text, too.

**Comment by ISN-Zurich** [comment]
We keep color coding to the absolute minimum: We only show the user selection and the correct statement in different colors so the user can identify them from all other items. We will also refrain from emphasizing wrong user selections by a red color. I don't see the confusion when the user can clearly identify which of the correct answers were not selected. 

Also we try not to over emphasize wrong answers for motivational reasons. 

In those cases when the selected answer is off screen and the user has to scroll the feedback view, then this is still consistent with the answer view, in which the user also had to scroll to get to the answer.
