### ISSUE TITLE
Statistics View Polishing

### ISSUE THREAD

**Issue by evangelia-mitsopoulou** [ISN-Zurich/ISN-Learning-Cards#106]
Change the visual layout of the statistics view according to the new requirements as following:
- title area to have a solid blue background color and a statistics icon on the left side of the title header
- all statistics metrics to be placed in one column, one below the other
- the time dependent statistics metrics to have a deeper grey background color and a vertical shadowed line that will separate the statistics metric value and the improvement status (arrow up, arrow down, equals)
- place a line for achievements. it will link to the achievements view

**Comment by ISN-Zurich** [comment]
Missing parts:
- sidebar "dash" icon for the improvement metrics
- add more top an dbottom space to the separator line
- add a seconds indicator for the speed value
- add text info for the handled cards value
- add select arrow on the achievements element

**Comment by evangelia-mitsopoulou** [comment]
done
