### ISSUE TITLE
Login View Polishing

### ISSUE THREAD

**Issue by evangelia-mitsopoulou** [ISN-Zurich/ISN-Learning-Cards#108]
Change the visual layout of the login view according to new requirements as following
- Login button on the bottom
- Username and password input fields to have a gradient grey background color and no input border, and an italic bar at the beginning
- Error and warning authentication messages to have a solid grey background, white font color and a loading icon on the left side. The whole message-block to hide  the username and password fields or to overlay them.
- title area to have a solid blue background color and and a lock-icon on the left side of the title header.
- background logo images

**Comment by ISN-Zurich** [comment]
- add fixed with for lms label and overflow ellipisis (text-overflow: ellipsis ) http://www.quirksmode.org/css/textoverflow.html
- if in horizontal view on small devices the login button overlays the form fields. Test for the screen size and hide the button if needed.

**Comment by evangelia-mitsopoulou** [comment]
above fixed.
additionally fixed: set in a dynamic way the width of the input fields (username, password) based on device width and device orientation mode.
