### ISSUE TITLE
Question View Polishing

### ISSUE THREAD

**Issue by evangelia-mitsopoulou** [ISN-Zurich/ISN-Learning-Cards#109]
Change the visual layout of the question view according to the new requirements as following:
- title area to have a solid blue background color and a question mark icon on the left side of the title header
- use grey gradient background color 
- place the forward button on the bottom of the screen
- use a blue italic bar on the left side of the question text

**Comment by ISN-Zurich** [comment]
Drop isn dash from the view in order to make better use of the screen estate.
