### ISSUE TITLE
Answer View Polishing

### ISSUE THREAD

**Issue by evangelia-mitsopoulou** [ISN-Zurich/ISN-Learning-Cards#110]
Change the visual layout of the answer view according to the new requirements as following:
- title area to have a solid blue background color and an icon on the left side of the title header according to the type of the question. use white font color for the question
- use grey gradient background color and shadows
- place the forward button on the bottom of the screen
- use a blue italic bar on the left side of each answer item
- use background logo images below the answer items

NOTE: Set as blue background color, the color of the whole selected by the user item

**Comment by ISN-Zurich** [comment]
Missing 
- separator space where the tick would go i. The feedback view
- title icon
- add a spacer margin at the bottom of the ul

**Comment by evangelia-mitsopoulou** [comment]
polished the answer view for all question types: added grey gradient and shadow on the bottom of the ul where needed. polished numeric question view.

**Comment by evangelia-mitsopoulou** [comment]
done
