### ISSUE TITLE
Feedback View Polishing

### ISSUE THREAD

**Issue by evangelia-mitsopoulou** [ISN-Zurich/ISN-Learning-Cards#111]
Change the visual layout of the feedback view according to the new requirements as following:
- title area to have a solid blue background color and an icon on the left side of the title header according to the type of the question. use white font color for the question
- use grey gradient background color and shadows
- place the forward button on the bottom of the screen
- use a blue italic bar on the left side of each answer item
- use background logo images below the answer items
- separate the answer text from the feedback icon (tick, wrong tick) with a vertical shadowed line
- use background logo images below the answer items
  . the title area of the feedback view will contain a visual representation of the textual feedback ( excellent, wrong, partially correct). For example there would be a circle with a default number of stars. In the cases where the feedback is excellent all the stars should be filled, in the case where the result is wrong none of the stars would be filled in and in the partially correct cases some of the star should be filled in.

NOTE: Set as blue background color, the color of the whole selected by the user item

**Comment by ISN-Zurich** [comment]
Missing
- icon on the title
- ticks are showing in the title bar and the next button.
- disable changing the selection tap
- NO RED CROSS _NEVER_ EVER
- height of the separator

**Comment by evangelia-mitsopoulou** [comment]
all the above Done.
TODO: numeric question feedback view, and feedbackmore view to look like question view
