### ISSUE TITLE
Courses List View Polishing

### ISSUE THREAD

**Issue by evangelia-mitsopoulou** [ISN-Zurich/ISN-Learning-Cards#112]
Change the visual layout of the courses list view according to the new requirements as following:
- title area to have a solid blue background color 
- use background logo images below the course items
- use grey gradient background color and shadows
- separate the course item with the statistics/loading item with a vertical shadowed line

**Comment by ISN-Zurich** [comment]
- Loading icon when tapping on the statistics icon is not displayed instead the statistics icon circles..

**Comment by evangelia-mitsopoulou** [comment]
fixed. also centered the courselist icon
