### ISSUE TITLE
automated login to PfP LMS

### ISSUE THREAD

**Issue by evangelia-mitsopoulou** [ISN-Zurich/ISN-Learning-Cards#117]
The only case where the user can enter the "exclusive" area although having selected the wrong LMS is the case where he has typed the Pfp username and password. We will display an ERROR MESSAGE to the user by saying "You have selected the wrong LMS but typed in your PfP account credentials. Do you want to stay in Pfp LMS?"-

**Comment by ISN-Zurich** [comment]
We will not proceed with this use case because of security limitations
