### ISSUE TITLE
Catch gesture events

### ISSUE THREAD

**Issue by ISN-Zurich** [ISN-Zurich/ISN-Learning-Cards#14]
catch the following events using the controller
- stretch
- pinch 
- swipe right 
- swipe left

The controller should trigger a related function in the active view.

**Comment by phish108** [comment]
Jquery mobile does not support multi touch events.

This blog gives an overview on alternatives.

http://www.queness.com/post/11755/11-multi-touch-and-touch-events-javascript-libraries

The most promising library is http://jgestures.codeplex.com/

**Comment by phish108** [comment]
I ran a comparison between jester (https://github.com/plainview/Jester/) and jguestures. 

I found that besides feeling faster jester delivers more consistent results for multi-touch gestures then jguestures.
