### ISSUE TITLE
(de-)activate the backend from the Ilias plugin administration

### ISSUE THREAD

**Issue by ISN-Zurich** [ISN-Zurich/ISN-Learning-Cards#145]
Desired behavior:

Administrators have to be able to activate or deactivate mobler cards via the plugin administration. 

if the backend has been deactivated by the API, then ALL backend services should respond with a "403 Forbidden" error. 

If the backend is active everything works as usual.

**Comment by evangelia-mitsopoulou** [comment]
List of HTTP status codes:  http://en.wikipedia.org/wiki/List_of_HTTP_status_codes
