### ISSUE TITLE
indicate that the service is deactivated to the clients

### ISSUE THREAD

**Issue by ISN-Zurich** [ISN-Zurich/ISN-Learning-Cards#146]
Current behavior:
If the backend is not installed  on a specific server it repsonds with  a 404 error to the client. This is visualized to user by making the specific server inactive for one day in the lms list view. We don't handle the case where the backend is installed but is deactivated.

Desired behavior: 

When the app starts it should check if the backend server is available. If the backend is installed but is deactivated then it needs to respond to the client with an 403 error in the appropriate model. This should be  visualized to the user as following:
- In LMS list view the user should be informed that the backend is temporarily gone. This warning message should be displayed under the specific lms for one hour.
- In Settings view there should be a deactivate message where it will be stated that the backend service is temporarily not available.

**Comment by evangelia-mitsopoulou** [comment]
Points in Time where the deactivation of Mobler Cards Backend Service can take place:

a) After the user has installed the app and before he starts doing anything else (authentication, registration to a different lms)
b) After the user has installed the app and has authenticated himself and has entered into the exclusive content.

Visualisation of deactivation of mobler cards on the above cases:

a) If the user tries to register in a different lms, we need to display on the lms list view for one hour, right below the specific server, that it will be temporarily unavailable. If the user will try to authenticate, an appropriate message should be visible on the login view for one hour. This message should also say that the user wont temporarily able to login into the system
b) In settings view there should be also a deactivation message where it will state to the user that temporarily we wont be able to synchronize with the backend. On all the other views, he will continue working as normal, but no synchronization will take place during the deactivation period.
