### ISSUE TITLE
Create interface logic for the app

### ISSUE THREAD

**Issue by ISN-Zurich** [ISN-Zurich/ISN-Learning-Cards#15]
Create views for all components of the app. 
- each view should identify itself
- it needs to be possible to switch between the views using the gesture definition

there are 7 views
1. the splash screen/ login screen  (tap on button to proceed to course list)
2. course list view:  tap on list item to switch to enter card question view; pinch gesture to switch to settings screen 
3. settings view: close button/stretch gesture to return to course list; logout button/ pinch gesture to logout confirmation screen
4. logout confirmation view: swipe (any)/pinch/ stretch: back to settings screen; logout: return to splash/login screen
5. card question view: swipe (any): next; tap (anywhere): switch to card answer view; pinch: to course list view
6. card answer view: swipe (any): next; tap on title area: back to question view; tap on done button: to feedback view; pinch: to course list view
7. card feedback view: swipe (any): to question view; pinch: to course list view

**Comment by evangelia-mitsopoulou** [comment]
on item 6, by swiping (any) on card answer view do we want to move to next question view? or next answer view of next question?

**Comment by phish108** [comment]
next question view. 

The learner cannot answer the next question without reading it first.

**Comment by evangelia-mitsopoulou** [comment]
thanks for the confirmation. 
it makes sense.
