### ISSUE TITLE
loading icon 

### ISSUE THREAD

**Issue by evangelia-mitsopoulou** [ISN-Zurich/ISN-Learning-Cards#156]
We need a "loading" icon, that will be displayed on the left side of the warning message on the login view, which is displayed when data are sent to the server during authentication.

We want a loading icon that will be displayed next to the title of the course on course list view when it is not fully loaded.

We want a loading icon when the app is launching on splash screen.

All the above can be visualized by the same loading icon.

**Comment by ISN-Zurich** [comment]
The arrows in the white circle don't look very nice. Maybe we can use just the arrows without the circle
