### ISSUE TITLE
Gradients

### ISSUE THREAD

**Issue by evangelia-mitsopoulou** [ISN-Zurich/ISN-Learning-Cards#172]
Selected Item Gradient (Dark Grey): Start #5e5e5e Stop:67% End:#8c8c8c
Light Grey (Stats, login input):Start #dbdbdb End:#fff
Normal Grey(Selected item before being select):Start #ddd End:#bebebe
Blue Header: Start:008cc7 End:0078ab
Go Button: Start:999 End:6a6a6a

**Comment by ISN-Zurich** [comment]
We need a stronger gradient for the title
