### ISSUE TITLE
Default setting for initial capitalization with text entries

### ISSUE THREAD

**Issue by rbschi** [ISN-Zurich/ISN-Learning-Cards#228]
It would be better not to have an initial capital letter with text entries (text gap), as our courses are typically english.

**Comment by evangelia-mitsopoulou** [comment]
The text entries contain the place holder "fill in the gap" which is written with small letters.
If you are talking about the actual textual solutions themselves then they are written by content authors in ILIAS. This is not related with the development of the code of the app.

**Comment by ISN-Zurich** [comment]
duplicates #231
