### ISSUE TITLE
Sometimes users add preceding and trailing p and br tags to the questions and feedbacks. They MUST be removed

### ISSUE THREAD

**Issue by ISN-Zurich** [ISN-Zurich/ISN-Learning-Cards#237]
Current behavior: 

Content creators add sometimes p tags and br into the questions and feedbacks in order to create a bit space at the top or the bottom of the question. 

THIS IS FORBIDDEN in Mobler Cards. 

Desired behavior:

Filter empty P-Tags and br-tags before displaying the question and feedback more view. The following algorithm should be  applied:
- insert the content as HTML
- then scan for leading, trailing and duplicate BR tags and empty P-Tags.
- remove all misplaced tags.

HINT: 
Once the text is cleaned it should (re)place the original text in the local storage.
the best time to do this cleaning is when the data is loaded from the backend

**Comment by evangelia-mitsopoulou** [comment]
Extra: Clean all script and img tags from question text and feedback view more text.
