### ISSUE TITLE
If a user marked no answer in multiple choice the feedback is "partially correct" and not "wrong"

### ISSUE THREAD

**Issue by phish108** [ISN-Zurich/ISN-Learning-Cards#27]
in multiple choice questions  the user can proceed to the feedback view without answering the question. In this case the feedback is partially correct, which should be "wrong".

**Comment by ISN-Zurich** [comment]
Test the answers as following
- if no correct answers are ticked, then the answer is ALWAYS wrong
- if all answers are ticked, then the answers is ALWAYS wrong
- if some correct answers are ticked, then the answer partially correct
- if all correct answers are ticked and any wrong answer is ticked, then the answer is partially correct
- if all correct answers are ticked and no wrong answer is ticked, then the answer is fully correct.
