### ISSUE TITLE
Handle  small questionpools

### ISSUE THREAD

**Issue by evangelia-mitsopoulou** [ISN-Zurich/ISN-Learning-Cards#59]
**Current Behavior**: When the question pool has 4 questions, the 3  of them are added in the QueueList and only one question remains available for answering. The app stops working when we try to move to the next question.

**Desired Behavior**: We want to empty the queueList when only one question is currently available  for answering.

**Comment by ISN-Zurich** [comment]
Alternative solution: 

Do not use the queue unless the question pool has more than n items, where n is a constant that is longer than the queue.

In order to avoid deadlocks we may use  2 \* queueLength before the queuing is activated. currently queueLength + 1 is used.

**Comment by evangelia-mitsopoulou** [comment]
It is solved now as following:
a) Use  of 2 \* queueLength to avoid deadlocks
b) Removed queue.push in the nextQuestion(). This function is returning only the index for the next question
c) The current question is added in the queue only when the quesiton pool is longer than the queue. This is done in the queueCurrentQuestion().
