### ISSUE TITLE
Question Text contains html elements

### ISSUE THREAD

**Issue by evangelia-mitsopoulou** [ISN-Zurich/ISN-Learning-Cards#60]
**Current Behavior**: Question text field contains in ILIAS html elements, div, strong, br.

**DesiredBehavior:** To remove these elements

**Comment by evangelia-mitsopoulou** [comment]
Use an appropriate expression with preg_replace( ) function.

**Comment by ISN-Zurich** [comment]
Alternatively, we could leave the tags and simply pass the html to the client and use JQuery's html() function to insert the content text into the view. 

I wonder where these tags come from as the question pool UI of Ilias only offers entering unformatted text?

**Comment by Bellina** [comment]
In the textfield is written something like:

`<div><strong>The question...</strong></div>`
`<div><br /></div>`

I used now JQuery's html()

**Comment by ISN-Zurich** [comment]
Fix confirmed with merge #62
