### ISSUE TITLE
Answer view for single choice questions is broken

### ISSUE THREAD

**Issue by phish108** [ISN-Zurich/ISN-Learning-Cards#70]
Current behaviour: 

In the latest version entering the answer view for a single choice question leads to a white screen.

Desired behaviour: 

Display the answerlist :-)

**Comment by evangelia-mitsopoulou** [comment]
Done!
Some head, refs..lines had remained during the merging and thats why it was not displayed properly

**Comment by ISN-Zurich** [comment]
I fixed it in the main master plus some more updates (e. g. Icons).

Dr. Christian Glahn
Instructional and Mobile Design
ISN Zürich

On 17.09.2012, at 09:53, "evangelia-mitsopoulou" <notifications@github.com<mailto:notifications@github.com>> wrote:

Done!
Some head, refs..lines had remained during the merging and thats why it was not displayed properly
