### ISSUE TITLE
StatisticsView

### ISSUE THREAD

**Issue by ISN-Zurich** [ISN-Zurich/ISN-Learning-Cards#75]
the speed in the statistics view shows a green arrow if the speed is larger than the previous avg. speed. 

However, in case of speed faster (smaller values) is better. 

I propose that the arrow colors should be inverse (red for up and green for down)  in the case of the speed value. What do you think?

**Comment by evangelia-mitsopoulou** [comment]
Done. Cannot check it on the screen yet..cause we need 24hrs.
Note: I would suggest that we add "ms"  after the value on the speed, so that the user knows what does this value mean. It could be any other speed-related metric such as number of cards per second..or anything else.
