### ISSUE TITLE
Can't return to question from feedback view

### ISSUE THREAD

**Issue by boderbolz** [ISN-Zurich/ISN-Learning-Cards#85]
Current behaviour:
After answering a question (Feedback View) it is not possible to return to the actual question.

Desired behaviour:
It should be possible to return to the actual question from the Feedback View.

**Comment by evangelia-mitsopoulou** [comment]
Do we want to keep/store the selected answers when we move back to answer View from Question View?

**Comment by boderbolz** [comment]
In my opinion: yes, we would...
