### ISSUE TITLE
Swipe and Pinch should work on new Android Versions

### ISSUE THREAD

**Issue by evangelia-mitsopoulou** [ISN-Zurich/ISN-Learning-Cards#87]
Current Behavior: Swipe and pinch gestures are working on iPhone and old android versions.

Desired Behavior: Swipe and pinch to work on new android versions.

**Comment by evangelia-mitsopoulou** [comment]
Hint: Modify and extend the already extended jester library

**Comment by evangelia-mitsopoulou** [comment]
Interesting remark on android incapabilities: http://www.html5rocks.com/en/mobile/touch/

**Comment by evangelia-mitsopoulou** [comment]
Swipe in newer Android Versions FIXED.

Solution:
1. Add the e.preventDefault() in jester touchStart and touchMove functions, after firstly initializing the value of prevent variable to be true.  Inspired by: http://code.google.com/p/android/issues/detail?id=19827 discussions. They use in their gest.html a button to change the value of prevent from false to true in order to start firing the events properly. We did that on the TouchMonitor of jester.
2.  Pass the prevent as argument in the touchStart  in order to resolve some problems with the input fields in the login view. The input fields were deactivated after the implementation of step 1. So, we need to pass the prevent in the tap (of input and username fields in login view) and set it to false in order not to execute the preventDefault in jester.
3. Transformed the clicks in taps in the done button in logout and settings view, because they were deactivated after the implementation of step 1. 
4. Changed a bit the way the general tap is handled on question view. We assigned the tapHandler to each DOM element separately in order to pass the prevent variable (= false) so that the preventDefault not to be executed in jester. Similar logic with step 2.
5. Added stopPropagation in CourseListView when tap on courseList Item. 
6. Added stopPropagation on QuestionView when tap to navigate to Answer View.
7. Changed the way handle Swipe was working on question view. Instead of showing gradually first the title and the the body we just use TransitionToQuestion. The reason for this change was that in newer Android versions, the change of icon title happened one gesture after the first swipe took place. Now they are all synchronized (title, body) and they swipe together, on the same step.

**Comment by ISN-Zurich** [comment]
Ah nice, so we placed the preventDefault call too late in the process.

Sent from my iPad

On 16.10.2012, at 17:30, "evangelia-mitsopoulou" <notifications@github.com<mailto:notifications@github.com>> wrote:

Swipe in newer Android Versions FIXED.

Solution:
1.  Add the e.preventDefault() in jester touchStart and touchMove functions.

**Comment by evangelia-mitsopoulou** [comment]
I rebased also the current "master" branch to iosVersion 2 on GitX..and checked on Xcode. Everything is working fine on iPhone too!

**Comment by evangelia-mitsopoulou** [comment]
swipe is working on newer android version
