### ISSUE TITLE
Actions are not counted until the user accesses the statistics view.

### ISSUE THREAD

**Issue by ISN-Zurich** [ISN-Zurich/ISN-Learning-Cards#97]
Current behavior: 
After logging in all actions that are performed before accessing the statistics view are ignored. This is related to the user login, because when forcing the application to restart, all actions are counted properly.

Desired behavior: 
All user actions should be tracked properly.

**Comment by evangelia-mitsopoulou** [comment]
This happens only the first time we launch the app. Any other time, it works fine, no matter if the user has clicked firstly the statistics view or not. It is probably related with the getfirstActive day function of the statistics model.
